version: "3.7"

services:
  database:
    image: mysql
    container_name: database-beedoo
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: beedoo_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql

  app:
    entrypoint: ./.docker/api/api-init-entrypoint.sh
    build: .
    container_name: api-beedoo
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  mysqldata:
    driver: local